spring:
  datasource:
    url: jdbc:postgresql://postgres.globalcorp-hr.svc:5432/sampledb
    username: 
    password: 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
